name: Test Meson-based installation and compilation

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - '**meson**'
  pull_request:
    paths:
      - '**meson**'

jobs:
  build_meson_linux:
    name: Meson on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo -H pip3 install meson
          python3 -m pip install protobuf grpcio-tools

      - name: Build with Meson
        run: |
          meson setup build -Dexamples=enabled
          ninja -C build/
          ./build/examples/meson_simple/simple

  build_meson_windows:
    name: Meson on Windows 2022
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install meson
          pip install protobuf grpcio-tools

      - name: Build with Meson
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          meson setup build -Dexamples=enabled
          ninja -C build/
          "build/examples/meson_simple/simple.exe"